finish_for_check
madaradayada/nodejs-rest-api pull request #4
Opened 2023-01-22 08:10 UTC by madaradayada

На проверку

2023-01-22 16:47 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-22 16:47 UTC, KhYulian commented on controllers/auth/getCurrent.js
> +            code: 200,
status: "ok",
code: 200, - зайві поля

2023-01-22 16:47 UTC, KhYulian commented on controllers/auth/getCurrent.js
> +            code: 200,
res.json({email, subscription})

2023-01-22 16:47 UTC, KhYulian commented on controllers/auth/getCurrent.js
> +
Переконайтесь, що prettier налаштований та працює

2023-01-22 16:47 UTC, KhYulian commented on controllers/contacts/addContact.js
> +        result: newContact,
Намагайтесь кникати надмірною вкладеності у респонсі. Можна значно спростити

2023-01-22 16:47 UTC, KhYulian commented on middlewares/authenticate.js
> +        if (!user || !user.token || user.token !== token) {
Якщо user'a не знайдено ви можете отримати помлку через !user.token використовуйте optional chaining !user?.token

2023-01-22 18:14 UTC, madaradayada commented on controllers/auth/getCurrent.js
> +            code: 200,
Виправлено

2023-01-22 18:14 UTC, madaradayada commented on controllers/auth/getCurrent.js
> +
Виправлено

2023-01-22 18:40 UTC, madaradayada commented on controllers/contacts/addContact.js
> +        result: newContact,
Виправлено

2023-01-22 19:34 UTC, madaradayada commented on middlewares/authenticate.js
> +        if (!user || !user.token || user.token !== token) {
Виправлено

2023-01-23 07:48 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-23 07:48 UTC, merged